### ISSUE TITLE
run_r is not defined

### ISSUE THREAD

**Issue by luciagrami** [jasonsahl/Phylomark#1]
Hello, I am trying to use phylomark but I get the following error with the test dataset

python .phylomark.py -r genomes/E2348_69.fasta -d genomes/ -t wga.tree

LOG: 2020/10/29 20:55:21 - Checking the path of dependencies
/home/lucia/anaconda3/envs/phylomark/bin/mothur
/home/lucia/anaconda3/envs/phylomark/bin/muscle
/home/lucia/anaconda3/envs/phylomark/bin/FastTree
/home/lucia/anaconda3/envs/phylomark/bin/blastn
/home/lucia/anaconda3/envs/phylomark/bin/makeblastdb
LOG: 2020/10/29 20:55:21 - Prepping sequences
LOG: 2020/10/29 20:55:26 - Number of sequences to process = 993011
LOG: 2020/10/29 20:55:26 - Starting the loop
Traceback (most recent call last):
  File "../phylomark.py", line 139, in <module>
    options.frag_length, options.parallel_workers)
  File "../phylomark.py", line 87, in main
    tree_loop(fasta_dict, "combined.seqs", tree, parallel_workers, run_r, num_refs)
NameError: name 'run_r' is not defined

Thanks!

**Comment by jasonsahl** [comment]
Please update the code and try again. I removed the run_r functionality in the updated versions
