### ISSUE TITLE
Distance.txt not found

### ISSUE THREAD

**Issue by akiledal** [jasonsahl/Phylomark#2]
Hi Jason, I'm running into this error when trying to use phylomark: `FileNotFoundError: [Errno 2] No such file or directory: 'distance.txt'` It seems like this error only shows up near the end of the run as the tool successfully completes many loops.

I ran this command with phylomark installed as suggested in in the Readme:
`./phylomark.py -g markers.fasta -d ../microcystis_genomes -t ../microcystis_genomes/microcystis.tre -p 8`

The full output is:

> LOG: 2022/03/27 20:30:21 - Checking the path of dependencies
> /Users/kiledal/miniconda3/envs/phylomark/bin/mothur
> /Users/kiledal/miniconda3/envs/phylomark/bin/muscle
> /Users/kiledal/miniconda3/envs/phylomark/bin/FastTree
> /Users/kiledal/miniconda3/envs/phylomark/bin/blastn
> /Users/kiledal/miniconda3/envs/phylomark/bin/makeblastdb
> LOG: 2022/03/27 20:30:27 - Number of sequences to process = 10
> LOG: 2022/03/27 20:30:27 - Starting the loop
> Traceback (most recent call last):
>   File "./phylomark.py", line 140, in <module>
>     options.frag_length, options.parallel_workers)
>   File "./phylomark.py", line 87, in main
>     tree_loop(fasta_dict, "combined.seqs", tree, parallel_workers, num_refs)
>   File "/Users/kiledal/bioinformatics/Phylomark/phylomark/util.py", line 364, in tree_loop
>     paste_files("name.txt","distance.txt","euc_dist.txt","polys.txt","length.txt","all_distances.txt")
>   File "/Users/kiledal/bioinformatics/Phylomark/phylomark/util.py", line 56, in paste_files
>     distance_file_lines = open(distance_file).readlines()
> FileNotFoundError: [Errno 2] No such file or directory: 'distance.txt'

**Comment by jasonsahl** [comment]
Anders,

I'm testing now, so please bear with me.

Jason

**Comment by akiledal** [comment]
I can confirm the new changes fixed this issue. Thank you!
